import * as THREE from "three";
import type { SaveData, Settings, Vec3 } from "../shared/types";
import { World } from "../world/World";
import { findSpawn } from "../world/generator";
import { Renderer } from "../rendering/Renderer";
import { Input } from "../input/Input";
import { Inventory } from "../inventory/Inventory";
import { AudioSystem } from "../audio/AudioSystem";
import { BlockId, BLOCKS, ItemId, toolTier } from "../world/blocks";
import { moveAxis, overlapsBlock, playerAABB } from "../player/collision";
import { raycastVoxel, type VoxelHit } from "../world/raycast";
import { craft, RECIPES } from "../crafting/recipes";
import { objectiveSatisfied } from "./objectives";
import { saveWorld } from "../persistence/db";
import type { UI } from "../ui/UI";

type Drop={id:number;count:number;position:THREE.Vector3;velocity:number;mesh:THREE.Mesh;age:number};
export class Game{
  readonly world:World;readonly inventory:Inventory;readonly spawn:Vec3;readonly player:Vec3;readonly velocity:Vec3={x:0,y:0,z:0};health=20;objective=0;completed=false;
  private renderer:Renderer;private input:Input;private audio:AudioSystem;private running=false;private stopped=false;private last=0;private accumulator=0;private grounded=false;private coyote=0;private jumpBuffer=0;private mining=0;private miningKey='';private target:VoxelHit|null=null;private placeCooldown=0;private bob=0;private landing=0;private stepTimer=0;private autosave=0;private debug=false;private fps=0;private frames=0;private fpsTime=0;private drops:Drop[]=[];
  constructor(readonly name:string,readonly seed:number,private settings:Settings,private ui:UI,save?:SaveData){
    this.world=new World(seed);if(save)this.world.applyEdits(save.edits);this.spawn=save?{...save.spawn}:findSpawn(seed);this.player=save?{...save.player}:{...this.spawn};this.health=save?.health??20;this.inventory=new Inventory(27,save?.inventory);this.objective=save?.objective??0;this.completed=save?.completed??false;
    this.renderer=new Renderer(this.world,settings);this.input=new Input(this.renderer.renderer.domElement,()=>settings.sensitivity);this.audio=new AudioSystem(()=>settings.volume);this.bind();
  }
  async start(){await this.renderer.init();this.running=true;this.ui.showGame();this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);this.lockPointer();requestAnimationFrame(t=>this.loop(t));}
  private bind(){
    const canvas=this.renderer.renderer.domElement;canvas.addEventListener('click',()=>{this.audio.start();if(!this.ui.isMenu()&&document.pointerLockElement!==canvas)this.lockPointer();});
    document.addEventListener('pointerlockchange',()=>{if(this.stopped)return;if(document.pointerLockElement===canvas){this.running=true;this.ui.showGame();}else if(this.running){this.running=false;this.input.clear();this.ui.pause();void this.save();}});
    addEventListener('keydown',e=>{if(this.stopped)return;if(e.code==='F3'){e.preventDefault();this.debug=!this.debug;}if(e.code==='F5'){e.preventDefault();void this.save(true);}if(!this.running)return;if(/^Digit[1-9]$/.test(e.code)){this.inventory.selected=Number(e.code.slice(5))-1;this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);}if(e.code==='KeyE'||e.code==='KeyC'){e.preventDefault();this.openInventory();}});
    this.ui.onResume=()=>{this.ui.showGame();this.lockPointer();};this.ui.onSave=()=>void this.save(true);this.ui.onQuit=()=>{void this.save().then(()=>{this.stop();this.ui.showTitle();});};this.ui.onCraft=id=>this.doCraft(id);this.ui.onMoveSlot=(a,b)=>{this.inventory.move(a,b);this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);};
  }
  private loop(time:number){if(this.stopped)return;const dt=Math.min(.1,(time-this.last)/1000||0);this.last=time;this.accumulator+=dt;while(this.accumulator>=1/60){if(this.running)this.fixed(1/60);this.accumulator-=1/60;}this.updateView(dt);this.renderer.render();this.frames++;this.fpsTime+=dt;if(this.fpsTime>=.5){this.fps=Math.round(this.frames/this.fpsTime);this.frames=0;this.fpsTime=0;}this.ui.debug(`FPS ${this.fps}\nXYZ ${this.player.x.toFixed(2)} ${this.player.y.toFixed(2)} ${this.player.z.toFixed(2)}\nCHUNK ${Math.floor(this.player.x/16)}, ${Math.floor(this.player.z/16)}\nLOADED ${this.world.chunks.size}\nTRIANGLES ${this.renderer.triangles()}\nSEED ${this.seed}\nGROUNDED ${this.grounded}`,this.debug);requestAnimationFrame(t=>this.loop(t));}
  private fixed(dt:number){
    const axis=this.input.axis(),len=Math.hypot(axis.x,axis.z)||1,sprint=this.input.keys.has('ShiftLeft')||this.input.keys.has('ShiftRight'),speed=sprint?6.2:4.5;
    const fwdX=-Math.sin(this.input.yaw),fwdZ=-Math.cos(this.input.yaw),rightX=Math.cos(this.input.yaw),rightZ=-Math.sin(this.input.yaw);const wishX=(rightX*axis.x+fwdX*axis.z)/len,wishZ=(rightZ*axis.x+fwdZ*axis.z)/len;
    const accel=this.grounded?35:9,decel=this.grounded?28:2;this.velocity.x=this.approach(this.velocity.x,wishX*speed,(axis.x||axis.z?accel:decel)*dt);this.velocity.z=this.approach(this.velocity.z,wishZ*speed,(axis.x||axis.z?accel:decel)*dt);
    if(this.input.consumeJump())this.jumpBuffer=.1;else this.jumpBuffer=Math.max(0,this.jumpBuffer-dt);this.coyote=this.grounded?.08:Math.max(0,this.coyote-dt);if(this.jumpBuffer>0&&this.coyote>0){this.velocity.y=7.2;this.grounded=false;this.coyote=0;this.jumpBuffer=0;this.audio.jump();}
    this.velocity.y=Math.max(-32,this.velocity.y-22*dt);moveAxis(this.player,'x',this.velocity.x*dt,(x,y,z)=>this.world.isSolid(x,y,z));moveAxis(this.player,'z',this.velocity.z*dt,(x,y,z)=>this.world.isSolid(x,y,z));const fallSpeed=-this.velocity.y;const hitY=moveAxis(this.player,'y',this.velocity.y*dt,(x,y,z)=>this.world.isSolid(x,y,z));this.grounded=hitY&&this.velocity.y<=0;if(hitY){if(fallSpeed>9)this.land(fallSpeed);this.velocity.y=0;}
    if(this.grounded&&(axis.x||axis.z)){this.stepTimer+=dt*speed;if(this.stepTimer>.43){this.stepTimer=0;const under=BLOCKS[this.world.get(Math.floor(this.player.x),Math.floor(this.player.y-.1),Math.floor(this.player.z))]!;this.audio.footstep(under.footstep);}}else this.stepTimer=0;
    const wheel=this.input.consumeWheel();if(wheel){this.inventory.selected=(this.inventory.selected+Math.sign(wheel)+9)%9;this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);}this.updateTarget();this.mine(dt);if(this.input.consumePlace()&&this.placeCooldown<=0)this.place();this.placeCooldown=Math.max(0,this.placeCooldown-dt);this.updateDrops(dt);this.autosave+=dt;if(this.autosave>25){this.autosave=0;void this.save();}
  }
  private updateView(dt:number){const moving=Math.hypot(this.velocity.x,this.velocity.z);this.bob=this.settings.headBob&&this.grounded?Math.sin(performance.now()*.012)*Math.min(.035,moving*.006):0;this.landing=Math.max(0,this.landing-dt*.4);this.renderer.setFov(this.settings.fov+(this.input.keys.has('ShiftLeft')&&moving>5?4:0));this.renderer.setCamera(this.player,this.input.yaw,this.input.pitch,this.bob,this.landing);this.renderer.rebuildDirty();}
  private updateTarget(){const cp={x:this.player.x,y:this.player.y+1.62,z:this.player.z},c=Math.cos(this.input.pitch),d={x:-Math.sin(this.input.yaw)*c,y:Math.sin(this.input.pitch),z:-Math.cos(this.input.yaw)*c};this.target=raycastVoxel(cp,d,5,(x,y,z)=>this.world.isSolid(x,y,z));this.renderer.target(this.target?.block);}
  private mine(dt:number){if(!this.input.mine||!this.target){this.cancelMine();return;}const {block}=this.target,key=`${block.x},${block.y},${block.z}`;if(key!==this.miningKey){this.miningKey=key;this.mining=0;}const id=this.world.get(block.x,block.y,block.z),def=BLOCKS[id]!;const selected=this.inventory.slots[this.inventory.selected],tier=toolTier(selected?.id??0);let multiplier=1;if(def.tool==='pickaxe')multiplier=tier>=def.tier?4:.16;this.mining+=dt*multiplier/Math.max(.1,def.hardness);this.ui.mining(this.mining);if(Math.floor(this.mining*6)!==Math.floor((this.mining-dt*multiplier/def.hardness)*6))this.audio.mine();if(this.mining>=1){this.world.edit(block.x,block.y,block.z,BlockId.Air);this.audio.break();if(def.drop&&!(def.tool==='pickaxe'&&tier<def.tier))this.spawnDrop(def.drop,block);if(selected&&toolTier(selected.id)>0)this.inventory.damageSelected();this.advance({kind:'pickup',id:def.drop});this.cancelMine();}}
  private cancelMine(){this.mining=0;this.miningKey='';this.ui.mining(0);}
  private place(){if(!this.target)return;const p=this.target.adjacent,s=this.inventory.slots[this.inventory.selected];if(!s||!BLOCKS[s.id]?.placeable)return this.ui.message('Select a placeable block');if(this.world.get(p.x,p.y,p.z)!==BlockId.Air&&this.world.get(p.x,p.y,p.z)!==BlockId.Water)return;if(overlapsBlock(playerAABB(this.player),p.x,p.y,p.z))return this.ui.message('Cannot place inside yourself');this.world.edit(p.x,p.y,p.z,s.id);this.inventory.consumeSelected();this.audio.place();this.placeCooldown=.18;this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);this.advance({kind:'place',id:s.id});if(s.id===BlockId.Beacon){this.renderer.addBeacon(p);this.audio.beacon();this.ui.complete();}}
  private spawnDrop(id:number,p:Vec3){const colors:Record<number,number>={[BlockId.Log]:0x9f6737,[BlockId.Cobblestone]:0x788486,[ItemId.Coal]:0x25292a,[ItemId.Crystal]:0x52e6f0};const mesh=new THREE.Mesh(new THREE.BoxGeometry(.25,.25,.25),new THREE.MeshLambertMaterial({color:colors[id]??0xc7d48d}));mesh.position.set(p.x+.5,p.y+.65,p.z+.5);this.renderer.scene.add(mesh);this.drops.push({id,count:1,position:mesh.position,velocity:1.5,mesh,age:0});}
  private updateDrops(dt:number){for(let i=this.drops.length-1;i>=0;i--){const d=this.drops[i]!;d.age+=dt;d.velocity-=16*dt;const ny=d.position.y+d.velocity*dt;if(this.world.isSolid(Math.floor(d.position.x),Math.floor(ny-.14),Math.floor(d.position.z))){d.velocity=0;d.position.y=Math.floor(ny-.14)+1.14;}else d.position.y=ny;d.mesh.rotation.y+=dt*1.8;d.mesh.position.y+=Math.sin(d.age*3)*.0008;if(d.position.distanceTo(new THREE.Vector3(this.player.x,this.player.y+1,this.player.z))<1.6){if(this.inventory.add(d.id,d.count)===0){this.renderer.scene.remove(d.mesh);d.mesh.geometry.dispose();(d.mesh.material as THREE.Material).dispose();this.drops.splice(i,1);this.audio.pickup();this.advance({kind:'pickup',id:d.id});this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);}}else if(d.age>600){this.renderer.scene.remove(d.mesh);this.drops.splice(i,1);}}}
  private nearBench(){for(let y=-2;y<=2;y++)for(let z=-4;z<=4;z++)for(let x=-4;x<=4;x++)if(this.world.get(Math.floor(this.player.x)+x,Math.floor(this.player.y)+y,Math.floor(this.player.z)+z)===BlockId.CraftingBench)return true;return false;}
  private openInventory(){this.running=false;document.exitPointerLock();this.ui.inventory(this.inventory,this.nearBench());}
  private doCraft(id:string){const recipe=RECIPES.find(r=>r.id===id);if(!recipe||!craft(this.inventory,recipe,this.nearBench()))return this.ui.message('Missing ingredients or crafting bench');this.audio.craft();this.advance({kind:'craft',id:recipe.output.id});this.ui.inventory(this.inventory,this.nearBench());this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);void this.save();}
  private advance(event:{kind:string;id:number}){if(this.completed)return;if(objectiveSatisfied(this.objective,event,id=>this.inventory.count(id))){this.objective++;this.audio.pickup();this.ui.message(this.objective>=8?'Expedition complete':'Objective complete');if(this.objective>=8)this.completed=true;this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);}}
  private land(speed:number){this.audio.land();this.landing=Math.min(.12,(speed-8)*.015);if(speed>12){const damage=Math.floor((speed-10)*1.6);this.health=Math.max(0,this.health-damage);this.audio.damage();this.ui.damage();this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);if(this.health<=0)this.respawn();}}
  private respawn(){this.player.x=this.spawn.x;this.player.y=this.spawn.y;this.player.z=this.spawn.z;this.velocity.x=this.velocity.y=this.velocity.z=0;this.health=20;this.ui.message('Recovered at the expedition camp');this.ui.renderHUD(this.inventory,this.health,this.objective,this.completed);}
  async save(announce=false){await saveWorld({version:1,name:this.name,seed:this.seed,edits:[...this.world.edits],player:{...this.player},spawn:{...this.spawn},health:this.health,inventory:this.inventory.serialize(),objective:this.objective,completed:this.completed,savedAt:Date.now()});if(announce)this.ui.message('World saved');}
  stop(){this.stopped=true;this.running=false;document.exitPointerLock();}
  private lockPointer(){try{const result=this.renderer.renderer.domElement.requestPointerLock();void result?.catch(()=>this.ui.message('Click the world to capture the mouse'));}catch{this.ui.message('Click the world to capture the mouse');}}
  private approach(v:number,target:number,delta:number){return v<target?Math.min(v+delta,target):Math.max(v-delta,target);}
}
