export const template=`
<main id="viewport" aria-label="Blockworks game viewport"></main>
<section id="title" class="screen active"><div class="panel hero"><div class="eyebrow">WATTFULL EXPERIMENTAL // 01</div><h1>BLOCK<span>WORKS</span></h1><p>Survey the wild grid. Shape tools. Raise a signal.</p><div class="menu"><button id="continue">Continue</button><button id="new-world" class="primary">New World</button><button data-open="settings">Settings</button><button data-open="controls">Controls</button><button id="delete-world" hidden>Delete Saved World</button><a href="/experimental">Return to Wattfull</a></div><small>Local single-player expedition · saves stay in this browser</small></div></section>
<section id="new-dialog" class="screen"><form class="panel modal"><div class="eyebrow">NEW EXPEDITION</div><h2>Create a world</h2><label>World name<input id="world-name" value="Frontier 01" maxlength="32"></label><label>Seed<input id="world-seed" placeholder="Optional word or number"></label><div class="row"><button type="button" data-close>Cancel</button><button type="submit" class="primary">Create World</button></div></form></section>
<section id="settings" class="screen"><div class="panel modal"><div class="eyebrow">CALIBRATION</div><h2>Settings</h2><label>Render distance <output id="render-out"></output><input id="render-distance" type="range" min="3" max="8"></label><label>Field of view <output id="fov-out"></output><input id="fov" type="range" min="60" max="95"></label><label>Mouse sensitivity<input id="sensitivity" type="range" min="1" max="5" step=".1"></label><label>Master volume<input id="volume" type="range" min="0" max="1" step=".05"></label><label class="check"><input id="head-bob" type="checkbox"> Head bob</label><label class="check"><input id="objectives" type="checkbox"> Show objectives</label><button data-close>Done</button></div></section>
<section id="controls" class="screen"><div class="panel modal"><div class="eyebrow">FIELD MANUAL</div><h2>Controls</h2><dl><dt>Move</dt><dd>W A S D</dd><dt>Look</dt><dd>Mouse</dd><dt>Jump / Sprint</dt><dd>Space / Shift</dd><dt>Mine / Place</dt><dd>Left / Right mouse</dd><dt>Inventory</dt><dd>E</dd><dt>Crafting</dt><dd>C</dd><dt>Hotbar</dt><dd>1–9 / wheel</dd><dt>Debug</dt><dd>F3</dd><dt>Save</dt><dd>F5</dd></dl><button data-close>Done</button></div></section>
<section id="pause" class="screen"><div class="panel modal"><div class="eyebrow">EXPEDITION PAUSED</div><h2>Blockworks</h2><div class="menu"><button id="resume" class="primary">Resume</button><button id="save">Save World</button><button data-open="settings">Settings</button><button id="quit">Save & Return to Title</button></div></div></section>
<section id="inventory" class="screen"><div class="panel inventory-panel"><header><div><div class="eyebrow">FIELD KIT</div><h2>Inventory</h2></div><button data-close>Close [E]</button></header><div class="inventory-layout"><div><h3>Pack</h3><div id="inventory-grid" class="slots"></div></div><div><h3>Crafting</h3><div id="recipes"></div></div></div></div></section>
<div id="hud" hidden><div id="objective"><small>CURRENT OBJECTIVE</small><b id="objective-text"></b></div><div id="health"></div><div id="crosshair"></div><div id="mine-progress"><i></i></div><div id="hotbar" class="slots"></div><div id="message"></div><div id="debug" hidden></div></div>
<div id="damage"></div><div id="completion" class="screen"><div class="panel hero"><div class="eyebrow">SIGNAL ESTABLISHED</div><h2>THE BEACON IS ONLINE</h2><p>Your introductory expedition is complete. The frontier remains open—keep building.</p><button data-close>Continue</button></div></div>`;
